### ISSUE TITLE
プラグイン追加時の初期データ登録処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Frames#13]
テーブル名とデータのJSONがあれば、初期データとして登録するイメージです。

https://github.com/NetCommons3/CircularNotices/issues/33

**Comment by s-nakajima** [comment]
Pluginテーブルに初期値フィールドを持たせて、フレーム追加時にデフォルトで作るイメージ。
ただ、現状、回覧板・アンケートなど個別で登録していて、それで問題ないため、いったんCloseする。
