### ISSUE TITLE
フレームから呼び出す各プラグインのaction名について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Frames#2]
プラグイン名/コントローラー名（プラグイン名と同じ）/index/フレームID
を呼び出しているが、
indexアクションは一覧のイメージが強いため、理解しづらい。
手段としては、
・プラグイン側で初期呼び出しアクションを指定できるようにする。
・viewアクションに固定する。
・defaultアクションに固定する。
の3択。

**Comment by kteraguchi** [comment]
少し話して出た案です。
・Pluginテーブルに初期呼び出しアクション名を登録しておく意見もあります。
もうちょい様子見ます。

**Comment by RyujiAMANO** [comment]
blogではblog_entry/indexをデフォにしたかったんでblogs/index からrequestActionしちゃいました

アクションだけでなくコントローラーを指定したいケースもあるってことで^^;

**Comment by kteraguchi** [comment]
おお。ですね。
コントローラーの指定ケース了解です。

**Comment by s-nakajima** [comment]
pluginsテーブルにdefault_action、default_setting_actionカラムを追加して、最初に呼び出すアクションを指定する。ただし、default_actionが空の場合は、(プラグイン名)/(プラグイン名)/indexを呼び出す。

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/NetCommons/issues/37
